### ISSUE TITLE
Microsoft Edgeにおける挙動が若干変

### ISSUE THREAD

**Issue by karia** [ssig33/pig-media-server#16]
pigの問題ではないと気もするけど…
-Cボタン押してコメントを入力したあとフォーカスが戻らない（≒ショートカットが使えなくなる）
-j,kを押したあと一時停止してしまう
-次の動画へ自動で移るとフルスクリーンが解除される

**Comment by ssig33** [comment]
フルスクリーンは対応難しい気がする。現状は video 要素が遷移のために消えるみたいな問題なので。そしてフルスクリーン化 API はユーザー入力からしか発火しないみたいな制限がある(じゃないとフルスクリーン広告とかバンバンでてきてやばいことになるので)。

F11 フルスクリーンモードがない Edge の問題という感じ。

j k 押した後の一時停止は実は IE 時代からある。 IE/Edge だったら J K 押されたら再生ステータス把握しておいてシーク後にステータス再現みたいなコードいれる必要がある。

モーダルでたらフォーカス外れるという話は全く知らない。ただこれはブラウザコンポーネント使ってモーダル出してるところを自前でやるようにすれば対処できる。

**Comment by ssig33** [comment]
requestFullscreen が Edge でも動くので、 \<video\> 要素じゃなくてその外枠のブロック要素をフルスクリーン化するようにすれば対処可能か。それでいく。
